FROM node:20-alpine AS builder

WORKDIR /app

COPY server/package*.json ./
RUN npm ci --omit=dev

FROM node:20-alpine

WORKDIR /app

ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=55555

COPY --from=builder /app/node_modules ./node_modules
COPY server/ ./

EXPOSE 55555

CMD ["node", "server.js"]
